config/routes.rb
Rails.application.routes.draw do
 
  get 'samples/sample_answer'
  get 'sessions/new'
  get 'users/reference'
  get 'users/site'
  get 'users/question_index'
  get 'toppages/question_sample'
  get 'toppages/sample_1'
  get 'toppages/sample_2'
  get 'toppages/index'
  get 'toppages/about'
  get 'toppages/examination'
  
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create]
  resources :answers, only: [:show]
  resources :quizzes, only: [:show]
  resources :beginners, only: [:index, :show]
  resources :intermediates, only: [:index, :show]
  resources :uppers, only: [:index, :show]
  resources :samples, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ApplicationRecord
    has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
    
    validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
    
    has_secure_password;
    
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  before_action :require_user_logged_in
  
  def show
    @quiz = Quiz.find(params[:id])
    @quizzes = Quiz.all
    @question = Question.find(params[:id])
    @questions = @quiz.questions
    @answers = @questions.map do |question|
      params[question.id.to_s]
    end
  end
end

app/controllers/beginners_controller.rb
class BeginnersController < ApplicationController
  
  before_action :require_user_logged_in
  
  def index
    @quizzes = Quiz.where(level: 1)
  end

  def show
    @quiz = Quiz.find(params[:id])
    @questions = @quiz.questions
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  def index
    @quizzes = Quiz.where(level: 4)
  end

  def show
    @quiz = Quiz.find(params[:id])
    @questions = @quiz.questions
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    name = params[:session][:name]
    password = params[:session][:password]
    if login(name, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private 
  
  def login(name, password)
    @user = User.find_by(name: name)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  
  def index
  end
  
  def question_sample
  end
end

app/controllers/uppers_controller.rb
class UppersController < ApplicationController
  
  before_action :require_user_logged_in
  
  def index
    @quizzes = Quiz.where(level: 3)
  end

  def show
    @quiz = Quiz.find(params[:id])
    @questions = @quiz.questions
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :require_user_logged_in, only: [:show, :reference, :site]
  
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザを新しく登録しました"
      redirect_to login_path
    else
      flash.now[:danger] = "ユーザの登録に失敗しました"
      render :new
    end
  end
  
  def reference
  end
  
  def site
  end
  
  private 
  
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beginners_helper.rb
module BeginnersHelper
end

app/helpers/intermediates_helper.rb
module IntermediatesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/sample_helper.rb
module SampleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
  
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/upper_helper.rb
module UpperHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/show.html.erb
<div class="row">
        <div class = "question_answer">
            <h2><%= @quiz.content%>　回答</h2>
            <ul>
                <li class = "question_sentence">問題１：<%= @questions.first.content %></li>
                <li>あなたの答え：<%= @answers[0] %></li>
                <% if @answers[0] == @questions.first.correct_answer %>
                    <li style="color: blue; font-weight: bold;">正解です。</li>
                <% elsif %>
                    <li style="color: red; font-weight: bold;">不正解です。</li>
                <% end %>
                <li><%= @questions.first.explanation %></li>
                
                <li class = "question_sentence">問題２：<%= @questions.second.content %></li>
                <li>あなたの答え：<%= @answers[1] %></li>
                <% if @answers[1] == @questions.second.correct_answer %>
                    <li style="color: blue; font-weight: bold;">正解です。</li>
                <% elsif %>
                    <li style="color: red; font-weight: bold;">不正解です。</li>
                <% end %>
                <li><%= @questions.second.explanation %></li>
                
                <li class = "question_sentence">問題３：<%= @questions.third.content %></li>
                <li>あなたの答え：<%= @answers[2] %></li>
                <% if @answers[2] == @questions.third.correct_answer %>
                    <li style="color: blue; font-weight: bold;">正解です。</li>
                <% elsif %>
                    <li style="color: red; font-weight: bold;">不正解です。</li>
                <% end %>
                <li><%= @questions.third.explanation %></li>
                
                <li class = "question_sentence">問題４：<%= @questions.fourth.content %></li>
                <li>あなたの答え：<%= @answers[3] %></li>
                <% if @answers[3] == @questions.fourth.correct_answer %>
                    <li style="color: blue; font-weight: bold;">正解です。</li>
                <% elsif %>
                    <li style="color: red; font-weight: bold;">不正解です。</li>
                <% end %>
                <li><%= @questions.fourth.explanation %></li>
                
                <li class = "question_sentence">問題５：<%= @questions.fifth.content %></li>
                <li>あなたの答え：<%= @answers[4] %></li>
                <% if @answers[4] == @questions.fifth.correct_answer %>
                    <li style="color: blue; font-weight: bold;">正解です。</li>
                <% elsif %>
                    <li style="color: red; font-weight: bold;">不正解です。</li>
                <% end %>
                <li><%= @questions.fifth.explanation %></li>
                
                <li class = "question_sentence">問題６：<%= @questions.last.content %></li>
                <li>あなたの答え：<%= @answers[6] %></li>
                <% if @answers[5] == @questions.last.correct_answer %>
                    <li style="color: blue; font-weight: bold;">正解です。</li>
                <% elsif %>
                    <li style="color: red; font-weight: bold;">不正解です。</li>
                <% end %>
                <li><%= @questions.last.explanation %></li>
            </ul>
            
            <div class = "back_to_index">
                <%= link_to "一覧に戻る", users_question_index_path, class: "btn btn-info" %>
            </div>
        </div>
</div>

app/views/beginners/index.html.erb
<div class = "container">
    <div class = "row">
        <div class = "col-sm-8 beginner_question">
            <h2>初級問題　一覧</h2>
            <% @quizzes.each do |quiz| %>
                <ul>
                    <li><%= link_to quiz.content, beginner_path(quiz.id), class: "beginner_question_list" %></li>
                </ul>
            <% end %>
        </div>
        <div class = "col-sm-4">
            <%= render 'layouts/asidebar' %>
        </div>
    </div>
</div>

app/views/beginners/show.html.erb
<div class = "container">
    <div class = "row">
        <div class = "question_contents">
            <h2><%= @quiz.content %></h2>
            <%= form_tag answer_path, method: :get do |f| %>
            <% @questions.each do |question| %>
            <div class = "beginner_question_content">
                <ul>
                    <li><%= question.content %></li>
                    
                    <ul>
                        <li><%= radio_button_tag question.id, question.choice_1 %>　<%= question.choice_1%></li>
                        <li><%= radio_button_tag question.id, question.choice_2 %>　<%= question.choice_2%></li>
                        <li><%= radio_button_tag question.id, question.choice_3 %>　<%= question.choice_3%></li>
                        <li><%= radio_button_tag question.id, question.choice_4 %>　<%= question.choice_4%></li>
                    </ul>
                </ul>
              </div>
            <% end %>
            
            <%= submit_tag "回答", class: "answer_button"%>
            <% end %>
        </div>
    </div>
</div>

app/views/samples/index.html.erb
<div class = "container">
    <div class = "row">
        <div class = "col-sm-8 sample_question">
            <h2>初級問題（トライアル）</h2>
            <% @quizzes.each do |quiz| %>
                <ul>
                    <li><%= link_to quiz.content, sample_path(quiz.id), class: "sample_question_link" %></li>
                </ul>
            <% end %>
        </div>
        <div class = "col-sm-4">
            <%= render 'layouts/asidebar' %>
        </div>
    </div>
</div>

app/views/samples/sample_answer.html.erb
<div class="row">
    <div class="col-sm-8">
        <div class = "question_answer_sample">
            <h2>回答</h2>
            <ul>
                <li>問題１</li>
                <li>猫は英語で「cat」なので、<span>正解は「２」</span></li>
                <li>問題２</li>
                <li>犬は英語で「dog」なので、<span>正解は「１」</span></li>
                <li>問題３</li>
                <li>虎は英語で「tiger」なので、<span>正解は「３」</span></li>
                <li>問題４</li>
                <li>40は英語で「forty」なので、<span>正解は「３」</span></li>
                <li>問題５</li>
                <li>カレンダーは英語で「calendar」なので、<span>正解は「１」</span></li>
                <li>問題６</li>
                <li>明日は英語で「tomorrow」なので、<span>正解は「２」</span></li>
            </ul>
            
            <div class = "recommendation card">
                <span style="font-weight: bold;">新規登録すれば、問題数も増え、より充実した問題に答えられる！<br>
                登録はたったの１分！さぁ、今すぐ簡単登録を！</span>
                <div class = "question_button">
                    <%= link_to "今すぐ新規登録！", signup_path, class: "btn btn-primary"%>
                </div>
            </div>
        </div>
    </div>
    
    <div class = "col-sm-4">
        <%= render 'layouts/asidebar' %>
    </div>
</div>

app/views/samples/show.html.erb
<div class = "container">
    <div class = "row">
        <div class = "question_contents_sample col-sm-8">
            <h2><%= @quiz.content %></h2>
            <div class = "question_content">
                <ul>
                    <li>学校は英語で？</li>
                    <ul>
                        <li>１：house</li>
                        <li>２：school</li>
                        <li>３：picture</li>
                        <li>４：lion</li>
                    </ul>
                </ul>
                
                <ul>
                    <li>家は英語で？</li>
                    <ul>
                        <li>１：house</li>
                        <li>２：school</li>
                        <li>３：picture</li>
                        <li>４：lion</li>
                    </ul>
                </ul>
                
                <ul>
                    <li>写真は英語で？</li>
                    <ul>
                        <li>１：house</li>
                        <li>２：school</li>
                        <li>３：picture</li>
                        <li>４：lion</li>
                    </ul>
                </ul>
                
                <ul>
                    <li>４０は英語で？</li>
                    <ul>
                        <li>１：forteen</li>
                        <li>２：fourty</li>
                        <li>３：forty</li>
                        <li>４：fourteen</li>
                    </ul>
                </ul>
                
                <ul>
                    <li>カレンダーは英語で？</li>
                    <ul>
                        <li>１：calendar</li>
                        <li>２：calender</li>
                        <li>３：carender</li>
                        <li>４：carendar</li>
                    </ul>
                </ul>
                
                <ul>
                    <li>明日は英語で？</li>
                    <ul>
                        <li>１：tommorrow</li>
                        <li>２：tomorrow</li>
                        <li>３：tommorow</li>
                        <li>４：tomorow</li>
                    </ul>
                </ul>
                </div>
            <div class = "answer_button">
                <%= link_to "回答", samples_sample_answer_path, class: "btn btn-primary" %>
            </div>
        </div>
        
        <div class = "sub col-sm-4">
            <%= render 'layouts/asidebar' %>
        </div>
    </div>
</div>

app/views/toppages/about.html.erb
<div class = "about">
    <div class = "container">
        <div class = "row">
            <div class = "col-md-8 main_about">
                <h2>Relish English</h2>
                <p>ここ最近で「グローバル」ということをよく耳にするようになったと感じられることは
                ありませんか？そして、ますます今後もその勢いは増していくと言われています。しかし、
                英語を勉強するとなると、膨大なお金がかかってしまいます。
                Relish Englishでは、そういった方々のニーズに応えるために作られました。
                皆さんもRelish Englishを活用して、これからのグローバル時代を一緒に楽しみましょう。</p>
                
                <h3>無料で英語学習！</h3>
                <p>語学の勉強には、その高い費用がつきものです。英語のための学習塾に通われたり、
                特に留学ともなると驚くほどの費用がかかってしまいます。Relish Englishは、そんなお金もなければ、
                時間もない方々のニーズに応えることができます。全ての問題に無料で気軽に挑戦することができ、
                学習のためのお金や時間がない方々にぴったりです。</p>
                
                <h3>実践的な問題が多数！</h3>
                <p>Relish Englishでは、下は小中学生レベルの初級問題から上はビジネスレベルの上級まで
                様々な問題にチャレンジすることができます。英語を勉強したてで、単語があまりわからなくても大丈夫！
                自分に合ったぴったりの問題に気軽に挑戦することができます。また、わかりやすい解説付きで
                より一層英語力を磨くことができます。</p>
                
                <h3>試験ごとの参考資料が見つかる！</h3>
                <p>英語の国際資格はたくさんあり、どの試験にはどの教材があっているのかわからないという
                方も多くいらっしゃることでしょう。当サイトでは、そういった問題を解消すべく、
                それぞれの試験に合ったぴったりの参考資料を紹介しており、自分にマッチした資料を簡単に見つけるができます。</p>
                
                <h3>おすすめの学習サイトが見つかる！</h3>
                <p>英語学習には、参考資料のみならず、サイトに関しても数多く存在し、どれがいいのか
                悩んでしまうことがあります。当サイトでは、様々な英語学習におすすめのオンラインサイトも紹介しており、
                簡単に見つけることができます。</p>
            </div>
            
            <div class = "col-md-4">
                <%= render 'layouts/asidebar' %>
            </div>
        </div>
    </div>
</div>

<script>
</script>

app/views/toppages/index.html.erb
<% if logged_in? %>

<div class="container">
    <div class="row">
        <div class="col-md-12 users_show_title">
            <p>こんにちは、 <%= current_user.name %>さん！</p>
        </div>
        
        <div class = "main_contents_show">
            <h2>問題に挑戦</h2>
            
            <div class = "container">
                <div class = "row">
                    <div class = "question_beginner col-md-4 each_link">
                        <div class = "beginner_question">
                            <img class="image d-block w-100" src="/assets/beginner_image.jpg" alt="First slide">
                            <%= link_to "初級", beginners_path, class: "font" %>
                        </div>
                    </div>
                    
                    <div class = "question_intermediate col-md-4 each_link">
                        <div class = "intermediate_question">
                            <img class="image d-block w-100" src="/assets/upper_image.jpg" alt="First slide">
                            <%= link_to "中級", intermediates_path, class: "font" %>
                        </div>
                    </div>
                    
                    <div class = "question_upper col-md-4 each_link">
                        <div class = "beginner_question">
                            <img class="image d-block w-100" src="/assets/intermediate_image.jpg" alt="First slide">
                            <%= link_to "上級", uppers_path, class: "font" %>
                        </div>
                    </div>
                </div>
            </div>
            
            <h2>おすすめの参考資料</h2>
            
            <div class = "container">
                <div class = "row">
                    <div class = "material_recommendation col-md-6 each_link">
                        <div class = "material1">
                            <a href="https://www.amazon.co.jp/%E3%82%84%E3%81%A3%E3%81%A6%E3%81%8A%E3%81%8D%E3%81%9F%E3%81%84%E8%8B%B1%E8%AA%9E%E9%95%B7%E6%96%87300-%E6%B2%B3%E5%90%88%E5%A1%BESERIES-%E6%9D%89%E5%B1%B1-%E4%BF%8A%E4%B8%80/dp/4777201546/ref=sr_1_2?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&crid=3C3WUIJGD0E59&dchild=1&keywords=%E3%82%84%E3%81%A3%E3%81%A6%E3%81%8A%E3%81%8D%E3%81%9F%E3%81%84%E8%8B%B1%E8%AA%9E%E9%95%B7%E6%96%87&qid=1609737785&s=books&sprefix=%E3%82%84%E3%81%A3%E3%81%A6%E3%81%8A%E3%81%8D%E3%81%9F%E3%81%84%2Cstripbooks%2C523&sr=1-2" target="_blank"><img class="image" src="/assets/reference_2.jpg" alt="First slide"></a>
                            <h3>やっておきたい英語長文</h3>
                            
                        </div>
                        
                        <div class = "material3">
                            <a href="https://www.amazon.co.jp/exec/obidos/ASIN/4757428782/alcownedmedia-22/" target="_blank"><img class="image" src="/assets/reference_4.jpg" alt="First slide"></a>
                            <h3>TOEIC L&R 究極のゼミ Part 7</h3>

                        </div>
                    </div>
                    
                    <div class = "material_recommendation col-md-6 each_link">
                        <div class = "material2">
                            <a href="https://www.amazon.co.jp/%E3%82%B9%E3%82%B3%E3%82%A2%E3%81%AB%E7%9B%B4%E7%B5%90%EF%BC%81IELTS%E5%BE%B9%E5%BA%95%E5%AF%BE%E7%AD%96%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%EF%BC%86%E5%95%8F%E9%A1%8C%E9%9B%86-%E3%82%B1%E3%83%93%E3%83%B3%E3%83%BB%E3%83%80%E3%83%B3/dp/4816358684/ref=sr_1_1?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&dchild=1&keywords=IETS+%E5%BE%B9%E5%BA%95%E5%AF%BE%E7%AD%96&qid=1609737695&s=books&sr=1-1-spell" target="_blank"><img class="image" src="/assets/reference_5.jpg" alt="First slide"></a>
                            <h3>IELTS 徹底対策　<br>テキスト＆問題集</h3>
                            
                        </div>
                        
                        <div class = "material4">
                            <a href="https://www.amazon.co.jp/%E8%8B%B1%E8%AA%9E%E3%83%A9%E3%82%A4%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%AB%E3%83%96%E3%83%83%E3%82%AF-%E7%AC%AC2%E7%89%88-%E6%AD%A3%E3%81%97%E3%81%8F%E4%BC%9D%E3%81%88%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AE%E6%96%87%E6%B3%95%E3%83%BB%E8%AA%9E%E6%B3%95%E3%83%BB%E5%8F%A5%E8%AA%AD%E6%B3%95-%E3%83%87%E3%82%A4%E3%83%B4%E3%82%A3%E3%83%83%E3%83%89%E3%83%BB%E3%82%BB%E3%82%A4%E3%83%B3/dp/4887245165/ref=as_li_ss_il?_encoding=UTF8&pd_rd_i=4887245165&pd_rd_r=9784e87c-a3c3-11e8-8e0b-7b3f98da7b92&pd_rd_w=RNKXN&pd_rd_wg=wkU2K&pf_rd_i=desktop-dp-sims&pf_rd_m=AN1VRQENFRJN5&pf_rd_p=4ef5676d-7b63-427d-8125-ba3be88d6f4f&pf_rd_r=HNWAJBECYF44W2B5CXF2&pf_rd_s=desktop-dp-sims&pf_rd_t=40701&psc=1&refRID=HNWAJBECYF44W2B5CXF2&linkCode=li2&tag=konoeigokyouz-22&linkId=d7776bec9a90e4576447c5a47913ddb8&language=ja_JP" target="_blank"><img class="image" src="/assets/reference_6.jpg" alt="First slide"></a>
                            <h3>英語ライティング<br>ルールブック</h3>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<% else %>
<div class = "top_contents">
    <div class = "main_title">
        <h2>Relish Englishとは？</h2>
        <p id="main_sentence">これからのグローバル時代に欠かせない「英語力」。みなさんは、どうやって勉強していますか？
        Relish Englishでは、これから英語の資格を取ろうと思っている人が勉強するための学習サイトです。
        皆さんもRelish Englishを使って一緒にグローバルな世界を楽しみましょう！</p>
        <%= link_to "サンプル問題を解く", samples_path, class: "btn btn-primary"%>
        
        <p style="margin-top: 60px;" id="main_title_second">また、新規登録すればより充実した問題を解くことができます！</p>
        <%= link_to '今すぐ新規登録', signup_path, class: 'btn btn-primary' %>
        
        <img class="image" src="/assets/relish_english_top.jpg" alt="First slide">
    </div>
</div>
    <div class = "merit_registration">
        <h2>登録をすると</h2>
        <div class = "container">
            <div class = "row">
                <div class = "col-md-6 left">
                    <div class = "first">
                        <!--<img class="u-max-full-width image_merit" src="assets/person-smartphone-office-table.jpg" alt="First slide">-->
                        <h3>無料で英語学習</h3>
                        <p>英語を勉強するとなると、色々と費用がかかってしまいますが、Relish Englishは、全て無料で問題にチャレンジすることができます。</p>
                    </div>
                    
                    <div class = "second">
                        <!--<img class="u-max-full-width image_merit" src="assets/person-smartphone-office-table.jpg" alt="First slide">-->
                        <h3>実践的な問題に挑戦できる</h3>
                        <p>問題のレベルも初級から上級者向けまでより多種多様で自分に合った問題に無理なく挑戦することができます。</p>
                    </div>
                </div>
                
                <div class = "col-md-6 right">
                    <div class = "first">
                        <!--<img class="u-max-full-width image_merit" src="assets/person-smartphone-office-table.jpg" alt="First slide">-->
                        <h3>自分に合った資料が見つかる</h3>
                        <p>英語には、様々な国際資格が存在しますが、Relish Englishでは、それぞれの資格に合った参考資料をご覧になることができます。</p>
                    </div>
                    
                    <div class = "second">
                        <!--<img class="u-max-full-width image_merit" src="assets/person-smartphone-office-table.jpg" alt="First slide">-->
                        <h3>おすすめサイトが見つかる</h3>
                        <p>また、英語学習にぴったりの様々なおすすめサイトを簡単に見つけることができます。</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class = "easy_registration">
        <h2>登録は簡単！</h2>
        <div class = "container">
            <div class = "row">
                <div class = "col-md-6 image_side">
                    <img class="u-max-full-width image" src="assets/signup_page_image.png" alt="First slide">
                </div>
                
                <div class = "col-md-6 explanation_side">
                    <p>登録時間はたったの<strong>３０秒！</strong><br>
                    登録時には、「ログインユーザ名」「ログインパスワード」のみ！！<br>
                    <%= link_to '今すぐ新規登録', signup_path, class: 'btn btn-primary' %>
                    
                </div>
            </div>
        </div>
    </div>

<% end %>

app/views/toppages/question_sample.html.erb
<div class = "question_sample">
    <div class = "container">
        <div class = "row">
            <div class = "main_contents_question_sample col-md-8">
                <h2>問題を解く</h2>
                
                <ul>
                    <li><%= link_to "初級問題１", toppages_sample_1_path %></li>
                    <li><%= link_to "初級問題２", toppages_sample_2_path %></li>
                </ul>
            </div>
            
            <div class = "sub_area col-md-4">
                <%= render 'layouts/asidebar' %>
            </div>
        </div>
    </div>
</div>

app/views/toppages/sample_1.html.erb
<div class = "sample_1">
    <div class ="container">
        <div class = "row">
            <div class = "main_contents_sample_1 col-md-8">
                
            </div>
            
            <div class = "sub_area col-md-4">
                <%= render 'layouts/asidebar' %>
            </div>
        </div>
    </div>
</div>

app/views/toppages/sample_2.html.erb
<div class = "sample_1">
    <div class ="container">
        <div class = "row">
            <div class = "main_contents_sample_2 col-md-8">
                
            </div>
            
            <div class = "sub_area col-md-4">
                <%= render 'layouts/asidebar' %>
            </div>
        </div>
    </div>
</div>

app/views/uppers/index.html.erb
<div class = "container">
    <div class = "row">
        <div class = "col-sm-8 upper_question">
            <h2>上級問題　一覧</h2>
            <% @quizzes.each do |quiz| %>
                <ul>
                    <li><%= link_to quiz.content, upper_path(quiz.id) %></li>
                </ul>
            <% end %>
        </div>
        <div class = "col-sm-4">
            <%= render 'layouts/asidebar' %>
        </div>
    </div>
</div>

app/views/uppers/show.html.erb
<div class = "container">
    <div class = "row">
        <div class = "question_contents">
            <h2><%= @quiz.content %></h2>
            <%= form_tag answer_path, method: :get do |f| %>
            <% @questions.each do |question| %>
            <div class = "upper_question_content">
                <ul>
                    <li><%= question.content %></li>
                    
                    <ul>
                        <li><%= radio_button_tag question.id, question.choice_1 %>　<%= question.choice_1%></li>
                        <li><%= radio_button_tag question.id, question.choice_2 %>　<%= question.choice_2%></li>
                        <li><%= radio_button_tag question.id, question.choice_3 %>　<%= question.choice_3%></li>
                        <li><%= radio_button_tag question.id, question.choice_4 %>　<%= question.choice_4%></li>
                    </ul>
                </ul>
              </div>
            <% end %>
            
            <%= submit_tag "回答", class: "answer_button"%>
            <% end %>
        </div>
    </div>
</div>