config/routes.rb
Rails.application.routes.draw do
 
  get 'samples/sample_answer'
  get 'sessions/new'
  get 'users/reference'
  get 'users/site'
  get 'users/question_index'
  get 'toppages/question_sample'
  get 'toppages/sample_1'
  get 'toppages/sample_2'
  get 'toppages/index'
  get 'toppages/about'
  get 'toppages/examination'
  
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create]
  resources :answers, only: [:show]
  resources :quizzes, only: [:show]
  resources :beginners, only: [:index, :show]
  resources :intermediates, only: [:index, :show]
  resources :uppers, only: [:index, :show]
  resources :samples, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ApplicationRecord
    has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
    
    validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
    
    has_secure_password;
    
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  before_action :require_user_logged_in
  
  def show
    @quiz = Quiz.find(params[:id])
    @quizzes = Quiz.all
    @question = Question.find(params[:id])
    @questions = @quiz.questions
    @answers = @questions.map do |question|
      params[question.id.to_s]
    end
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  def index
    @quizzes = Quiz.where(level: 4)
  end

  def show
    @quiz = Quiz.find(params[:id])
    @questions = @quiz.questions
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    name = params[:session][:name]
    password = params[:session][:password]
    if login(name, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private 
  
  def login(name, password)
    @user = User.find_by(name: name)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/uppers_controller.rb
class UppersController < ApplicationController
  
  before_action :require_user_logged_in
  
  def index
    @quizzes = Quiz.where(level: 3)
  end

  def show
    @quiz = Quiz.find(params[:id])
    @questions = @quiz.questions
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :require_user_logged_in, only: [:show, :reference, :site]
  
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザを新しく登録しました"
      redirect_to login_path
    else
      flash.now[:danger] = "ユーザの登録に失敗しました"
      render :new
    end
  end
  
  def reference
  end
  
  def site
  end
  
  private 
  
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beginners_helper.rb
module BeginnersHelper
end

app/helpers/intermediates_helper.rb
module IntermediatesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/sample_helper.rb
module SampleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
  
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/upper_helper.rb
module UpperHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_answer.html.erb
<div class = "question_answer">
    <h2><%= @quiz.content%>回答</h2>
    <ul>
        <li>問題１</li>
        <li></li>
        <li>問題２</li>
        <li></li>
        <li>問題３</li>
        <li></li>
    </ul>
</div>

app/views/layouts/_asidebar.html.erb
<% if logged_in? %>
    <div class = "sub_area">
        <div class="list-materials">
            <div class="list-title">試験について</div>
            <ul class="ichiran">
                <li class="nav-item"><%= link_to 'TOEIC', toppages_examination_path(anchor: "toeic"), class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to 'TOEFL', toppages_examination_path(anchor: "toefl"), class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to 'IELTS', toppages_examination_path(anchor: "ielts"), class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to 'FCE', toppages_examination_path(anchor: "fce"), class: 'nav-link' %></li>
            </ul>
        </div>
    
      　<div class="list-materials">
            <div class="list-title">問題を解く</div>
            <ul class="ichiran">
              <li><%= link_to "初級", beginners_path %></li>
              <li><%= link_to "中級", intermediates_path %></li>
              <li><%= link_to "上級", uppers_path %></li>
            </ul>
        </div>
        
        <div class="list-materials" style = "margin-top: 45px;">
            <div class="list-title">学習参考資料</div>
            <ul class="ichiran">
                <li class="nav-item"><%= link_to 'TOEIC', users_reference_path, class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to 'TOEFL', users_reference_path, class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to 'IELTS', users_reference_path, class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to 'FCE', users_reference_path, class: 'nav-link' %></li>
            </ul>
        </div>
    </div>
<% else %>
    <div class = "sub_area">
        <div class="list-materials">
            <div class="list-title">試験について</div>
            <ul class="ichiran">
                <li class="nav-item"><%= link_to 'TOEIC', toppages_examination_path(anchor: "toeic"), class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to 'TOEFL', toppages_examination_path(anchor: "toefl"), class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to 'IELTS', toppages_examination_path(anchor: "ielts"), class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to 'FCE', toppages_examination_path(anchor: "fce"), class: 'nav-link' %></li>
            </ul>
        </div>
    
       <div class="list-materials">
            <div class="list-title">問題を解く</div>
            <ul class="ichiran">
                <ul>
                    <li id="trial_sub"><%= link_to "初級問題（トライアル）", samples_path, class: "nav-link" %></li>
                </ul>
            </ul>
        </div>
    </div>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mb-4">
  <div class="footer_nav">
    <ul>
      <% if logged_in? %>
        <li class="nav-item"><%= link_to '概要', toppages_about_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to '試験について', toppages_examination_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to '問題を解く', users_question_index_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to '学習参考資料', users_reference_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to '学習サイト', users_site_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
      <% else %>
        <li class="nav-item"><%= link_to '概要', toppages_about_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to '試験について', toppages_examination_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to "問題を解く", samples_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <a class="navbar-brand" href="/">Relish English</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon toggle_icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
            <li class="nav-item"><%= link_to '概要', toppages_about_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to '試験について', toppages_examination_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to '問題を解く', users_question_index_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to '学習参考資料', users_reference_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to '学習サイト', users_site_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
          <% else %>
            <li class="nav-item"><%= link_to '概要', toppages_about_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to '試験について', toppages_examination_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to "問題を解く", samples_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_question.html.erb
<div class = "main_question">
    <h2><%= @quiz.content%></h2>
    
    
        <h3>問題１</h3>
        <ul>
        <li id = "question_sentence"><%= @questions.first.content%></li>
            <li>答え１：<%= @questions.first.choice_1%></li>
            <li>答え２：<%= @questions.first.choice_2%></li>
            <li>答え３：<%= @questions.first.choice_3%></li>
            <li>答え４：<%= @questions.first.choice_4%></li>
        </ul>
        
        <h3>問題２</h3>
        <ul>
        <li id = "question_sentence"><%= @questions.second.content%></li>
            <li>答え１：<%= @questions.second.choice_1%></li>
            <li>答え２：<%= @questions.second.choice_2%></li>
            <li>答え３：<%= @questions.second.choice_3%></li>
            <li>答え４：<%= @questions.second.choice_4%></li>
        </ul>
        
        <h3>問題３</h3>
        <ul>
        <li id = "question_sentence"><%= @questions.third.content%></li>
            <li>答え１：<%= @questions.third.choice_1%></li>
            <li>答え２：<%= @questions.third.choice_2%></li>
            <li>答え３：<%= @questions.third.choice_3%></li>
            <li>答え４：<%= @questions.third.choice_4%></li>
        </ul>
        
        <%= link_to "回答", answer_path %>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Relish English</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>